### ISSUE TITLE
FYI: Added XMLTestRunner to SikuliX package

### ISSUE THREAD

**Issue by RaiMan** [srittau/xmltestrunner#2]
reference: http.//sikulix.com

Hi Sebastian,

just for information (though I could write this in German ;-)

I am adding often asked/used Python packages, that are Jython compatible, to the SikuliX distribution beginning with version 1.1.0.

the others for now are HTMLTestRunner and the xl.... packages.

Since I have not tested yet, I use version 0.1 (hoping it runs with Jython 2.5) and version 0.2 (hoping it runs with Jython 2.7, which is bundled with Sikuli 1.1.0+).

As with HTMLTestrunner I will add the possibility to take a screenshot at failure and add the link to the XML output.

I have added the links from where I downloaded the 2 modules.

I will add information on the bundled packages on the sikulix.com later.

Do you have any requirements or suggestions what I should write?

Thanks 
Raimund aka RaiMan

**Comment by RaiMan** [comment]
no answer

**Comment by srittau** [comment]
I totally missed this issue, sorry about that! That said, I would recommend using [unittest-xml-reporting](https://github.com/xmlrunner/unittest-xml-reporting) instead of this module as it is basically unmaintained and unittest-xml-reporting is more powerful.

**Comment by RaiMan** [comment]
LOL, the world has turned since then ;-) but your sources are still in the SikuliX package.
I only did some room cleaning;-)

... but your sources are still in the SikuliX package.
No problem. I already read about the change and recommendation.
Will add to my docs.

All the best
